[package]
name = "serf"
version = "0.1.0"
authors = ["njent"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.1"
outer_cgi = "0.2.0"
