version: "3"

services:
  web:
    build:
      context: ./web
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    volumes: 
      - type: bind
        source: ./certs/apache-selfsigned.crt
        target: /usr/local/apache2/conf/server.crt
      - type: bind
        source: ./certs/apache-selfsigned.key
        target: /usr/local/apache2/conf/server.key

  db:
    image: mysql:5.5
    restart: always
    volumes: 
      - type: volume
        source: db_logs
        target: /var/log/mysql
      - type: volume
        source: db_data
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?mysql_root_password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?mysql_password}

  dbadmin:
    image: adminer:4
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db_logs:
  db_data:
